{
  "hash": "6a5b6591cd98082e0649e2487c82560b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Simple linear regression\nsubtitle: \"{{< fa book-open >}} Modeling Inference <br>{{< fa book >}} Data Science with R\"\nformat: live-html\nengine: knitr\nbibliography: references.bib\nwebr:\n  packages: \n    - tidyverse\n    - tidymodels\n    # - faraway\n    #- scales\n    #- ggridges\n    # - kableExtra\n  cell-options:\n    autorun: false\n  resources:\n    - https://raw.githubusercontent.com/data-science-with-r/modeling-inference/refs/heads/main/exercises/data/diabetes.csv\n---\n\n\n<!-- begin: webr fodder -->\n\n::: {.cell}\n\n:::\n\n\n::: {.cell edit='false'}\n```{webr}\n#| edit: false\n#| echo: false\n#| output: false\noptions(\"readr.edition\" = 1)\nlibrary(tidyverse)\n# Read the CSV file directly from the URL\ndiabetes <- read_csv(\"https://raw.githubusercontent.com/data-science-with-r/modeling-inference/refs/heads/main/exercises/data/diabetes.csv\")\n\n```\n:::\n\n\n<!-- end: webr fodder -->\n\n# Getting Started\n\nProgramming exercises are designed to provide an opportunity for you to put what you learn in the videos and readings. These exercises feature interactive code cells which allow you to write, edit, and run R code without leaving your browser.\n\nWhen the ▶️ Run Code button turns to a solid color (with no flashing bubble indicating that the document is still loading), you can interact with the code cells!\n\nWe invite you to think critically about the ethics questions associated with each graph before opening the solution box so you get the most out of this exercise.\n\n## Packages\n\nWe’ll use the **tidyverse** and **tidymodels** for this programming exercise. These are already installed for you to use!\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n\n## Motivation\n\nIt's important to learn statistical modeling, as it provides us the tools necessary to answer complex questions in a responsible, insightful manner.\n\nIn this programming exercise, we are going to be working with data that were published in the *Preventive Medicine* journal in 1997 [@SCHORLING199792]. In this dataset, 403 African Americans were interviewed in a study to understand the prevalence of obesity, diabetes, and other cardiovascular risk factors in central Virginia. We will fit simple linear regression models with different types of predictors to help best understand total cholesterol. Please read the data in below. \n\n\n::: {.cell}\n```{webr}\n#| label: load-kansas-data\ndiabetes <- read_csv(\"diabetes.csv\")\n\ndiabetes\n```\n:::\n\n\n\n## Dataset information\n\nBelow is a data key that shows subset of variables we are going to work with for this activity. The original data are located in the `faraway` package.\n\n| Variable Name | Description                                         |\n|---------------|-----------------------------------------------------|\n| chol          | Total Cholesterol                                   |\n| weight        | weight in pounds                                    |\n| frame         | factor with levels small, medium, large             |\n\n\n\nNow, let's explore these data!\n\n## Exploratory Data Analysis\n\n::: exercise\n\nBefore we fit a linear regression model, we are going to explore the data. Let' start with exploring our response variable of interest, cholesterol (`chol`). Find the mean and sd of the variable `chol` below. Note: the variable `chol` does have missing values.\n\n\n::: {.cell}\n```{webr}\n\n```\n:::\n\n\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Hint\n\nThink about the following code structure below, and what you want to be taking the mean of!\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiabetes |>\n  summarize(mean = mean(___, na.rm = ___), \n            sd = sd(___ , na.rm = ___))\n```\n:::\n\n:::\n\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiabetes |>\n  summarize(mean = mean(chol, na.rm = TRUE), \n            sd = sd(chol , na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n   mean    sd\n  <dbl> <dbl>\n1  208.  44.4\n```\n\n\n:::\n:::\n\n\n:::\n\n\n\n::: exercise\n\nNext, let's create a histogram of our response. What is the shape of the distribution?\n\n\n::: {.cell}\n```{webr}\n\n```\n:::\n\n\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Hint\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiabetes |>\n  ggplot(\n    aes(x = ___)\n  ) +\n  geom______()\n```\n:::\n\n:::\n\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiabetes |>\n  ggplot(\n    aes(x = chol)\n  ) +\n  geom_histogram() + \n  labs(title = \"Histogram of Cholesterol\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 1 row containing non-finite outside the scale range\n(`stat_bin()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](diabetes_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nThe distribution of cholesterol responses is roughly symmetric, with a couple additional observations out on the right tail.\n\n:::\n\n## Question of interest \n\nNow, we are going to explore the relationship between weight, and an individual's cholesterol. For this exercise, cholesterol (`chol`) is going to be our response, and our explanatory variable is going to be weight (`weight`).\n\n::: exercise\n\nFirst, let's create a scatterplot between cholesterol and weight. We also want to fit a least squares simple linear regression line through our data. Once we create the plot, what can we say about the relationship? \n\n\n::: {.cell}\n```{webr}\n\n```\n:::\n\n\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Hint\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiabetes |>\n  ggplot(\n    aes(x = ___, y = ____)\n  ) +\n  geom______() + \n  geom______(method = \"lm\" , se = F)\n```\n:::\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiabetes |>\n  ggplot(\n    aes(x = weight, y = chol)\n  ) +\n  geom_point() + \n  geom_smooth(method = \"lm\", se = F) + \n  labs(title = \"Relationship between weight and cholesterol\",\n       subtitle = \"with a line of best fit\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing non-finite outside the scale range\n(`stat_smooth()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](diabetes_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nIt appears that the relationship between weight and cholesterol is slightly positive. That is, as someone's weight increases, on average, their cholesterol increases according to these data. \n:::\n\n## Estimating the line of best fit. \n\nNow, let's use R to calculate the coefficients associated with the line of best fit your created above. The R code below uses **tidymodels** to specify a linear regression model with `cholesterol` as the response, and `weight` as the explanatory variable from the `diabetes` data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_fit <- linear_reg() |> \n  fit(chol ~ weight, data = diabetes)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term        | estimate|\n|:-----------|--------:|\n|(Intercept) |  194.986|\n|weight      |    0.074|\n\n\n:::\n:::\n\n\n::: exercise\n\nHow would you interpret the intercept?\n\nHow would you interpret the weight coefficient?\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\nIntercept: For a person who weighs 0 pounds, we would estimate their mean cholesterol to be 194.986 milligrams per deciliter.\n\nWeight: For a one pound increase in a person, we estimate on average, a 0.074 milligrams per deciliter increase in their cholesterol.\n\n:::\n\n## Outliers \n\nWe are going to investigate how adding outliers influences the line of best fit. First, we want you to: \n\n-- Create a new observation that has a value of 200 pounds, and a cholesterol value of 600. \n\n-- Create a new observation that has a value of 500 pounds, and a cholesterol value of 600. \n\nWe are going to re-estimate our line of best fit for each of these added observations. To create a new observation, please fill in the ____ with the appropriate values. Next, add this value to the exsisting data set using the `bind_rows()` function.\n\n::: exercise\n\n::: {.cell}\n```{webr}\nnew_obs <- tibble(\n  weight = ___,\n  chol = ____\n)\n\ndiabetes_new <- bind_rows(diabetes, new_obs)\n\ndiabetes_new[404,]\n```\n:::\n\n\nNow, re-run the following code below to see how your line has changed from above. Try this activity with at least our two suggested new observations. You are encouraged to explore more!\n\n\n::: {.cell}\n```{webr}\nlm_fit <- linear_reg() |> \n  fit(chol ~ weight, data = diabetes_new)\n\ntidy(lm_fit) |>\n  select(term, estimate) |>\n  kable(digits = 3)\n```\n:::\n\n:::\n\n\n::: {.callout-tip collapse=\"true\"}\n## Takeaways\n\n-- Outliers that are more towards the middle of the data have less influence on the estimated slope coefficient\n\n-- Outliers that are more towards the ends of the data have higher influence of the estimated slope coefficient\n:::\n\n## Modeling with a categorical variable \n\nSimple linear regression is not limited to using a single quantitative explanatory variable. We can also use a categorical variable. In this exercise, we are going to model our response variable cholesterol by a person's frame. \n\n::: exercise\n\nFit the appropriate simple linear regression model, and produce the estimates for the model.\n\n\n::: {.cell}\n```{webr}\nlm_fit <- linear_reg() |> \n  fit()\n\ntidy(lm_fit) |>\n  select(term, estimate) |>\n  kable(digits = 3)\n```\n:::\n\n\n\nWhy do you have a negative estimate?\n:::\n\n\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_fit <- linear_reg() |> \n  fit(chol ~ frame, data = diabetes)\n\ntidy(lm_fit) |>\n  select(term, estimate) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term        | estimate|\n|:-----------|--------:|\n|(Intercept) |  208.000|\n|framemedium |    5.538|\n|framesmall  |  -10.505|\n\n\n:::\n:::\n\n\nSome estimates are small because the estimates that are associated with levels of the categorical variable `frame` are **deviations** from the baseline group! Notice how we see estimates for medium and large, but not small. Small has been chosen to be the baseline group, and the other estimates are deviations from the baseline.\n\n:::\n\n\nWhen working with a single categorical variable, the estimates for cholesterol correspond to the sample mean cholesterol for each group!\n\n::: exercise \nTo verify this, please see the calculate the sample mean cholesterol for each frame group below, and relate these sample means to the deviations from the baseline above.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiabetes |>\n  filter(!is.na(frame)) |>\n  group_by(frame) |>\n  summarise(mean_chol = mean(chol, na.rm = T))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  frame  mean_chol\n  <chr>      <dbl>\n1 large       208 \n2 medium      214.\n3 small       197.\n```\n\n\n:::\n:::\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\nOur baseline estimated mean cholesterol for someone with a small frame is ~ 197 in both summary outputs. The baseline deviation for the medium group is 16.043. The calculated sample mean cholesterol for someone with a medium build is ~214, which is roughly 16 units away (not exact due to rounding). This relationship holds for the large frame group as well. \n::: \n\nWith this information in-mind, what is the appropriate interpretation for the 16.403 estimate? \n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\nFor someone with a medium frame, we estimate on average a 16.043 increase in cholesterol from those who have a small frame.\n\n:::\n\n## In Summary \n\n-- Simple linear regression can be used when our response variable is quantitative, and we have a single explanatory variable.\n\n-- Outliers have the ability to drastically influence our line of best fit. \n\n\n\n",
    "supporting": [
      "diabetes_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}