{
  "hash": "f7efec0d76accc14926e287813c537c4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Predicting income level with logistic regression\nsubtitle: \"{{< fa book-open >}} Modeling Inference <br>{{< fa book >}} Data Science with R\"\nformat: live-html\nengine: knitr\nbibliography: references.bib\nwebr:\n  packages: \n    - tidyverse\n    - tidymodels\n  cell-options:\n    autorun: false\n  resources:\n    - https://raw.githubusercontent.com/data-science-with-r/modeling-inference/refs/heads/main/exercises/data/income.csv\n---\n\n<!-- begin: webr fodder -->\n\n\n::: {.cell}\n\n:::\n\n\n\n\n::: {.cell edit='false'}\n```{webr}\n#| edit: false\n#| echo: false\n#| output: false\noptions(\"readr.edition\" = 1)\nlibrary(tidyverse)\n# Read the CSV file directly from the URL\nincome <- read_csv(\"https://raw.githubusercontent.com/data-science-with-r/modeling-inference/refs/heads/main/exercises/data/income.csv\")\n```\n:::\n\n\n<!-- end: webr fodder -->\n\n# Getting started\n\nProgramming exercises are designed to provide an opportunity for you to put what you learn in the videos and readings. These exercises feature interactive code cells which allow you to write, edit, and run R code without leaving your browser.\n\nWhen the ▶️ Run Code button turns to a solid color (with no flashing bubble indicating that the document is still loading), you can interact with the code cells!\n\n## Packages\n\nWe’ll use the **tidyverse** and **tidymodels** for this programming exercise. These are already installed for you to use!\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n## Motivation\n\nCensus data can help us predict income based on other variables, such as demographic, social, and economic variables. We can use this information to help gain deeper insights into the economic well-being of a population, which can help practically inform items such as strategic planning, and market analysis. In this programming exercise, we are going to explore the relationship between different predictors, and if an individual was making more or less than \\$50,000 USD a year in 1994 in the United States.\n\n## Data\n\nThe dataset we will be using for this exercise is from the 1994 Census database, extracted by Barry Becker. These data can be found on the [UCI Machine Learning Repository](https://archive.ics.uci.edu/dataset/2/adult). Expand the tab below to look at the data key.\n\n\n::: {.cell}\n```{webr}\n#| label: load-data\nincome <- read_csv(\"income.csv\") \n\nincome\n```\n:::\n\n\n::: {.callout-caution collapse=\"true\"}\n|                |                                                     |\n|----------------|-----------------------------------------------------|\n| Variable Name  | Description|\n| age            | Age                                                                                                                                                                                                                                                                                                                                                                                                                             |\n| workclass      | Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.                                                                                                                                                                                                                                                                                                                          |\n| education      | Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.                                                                                                                                                                                                                                                                          |\n| education-num  | Education Level as a number                                                                                                                                                                                                                                                                                                                                                                                                     |\n| marital-status | Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.                                                                                                                                                                                                                                                                                                                      |\n| occupation     | Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspect, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.                                                                                                                                                                                                       |\n| relationship   | Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.                                                                                                                                                                                                                                                                                                                                                             |\n| race           | White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.                                                                                                                                                                                                                                                                                                                                                                    |\n| sex            | Female, Male.                                                                                                                                                                                                                                                                                                                                                                                                                   |\n| native-country | United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands. |\n| income         | \\>50K, \\<=50K.                                                                                                                                                                                                                                                                                                                                                                                                                  |\n:::\n\n# Exploratory data analysis\n\n::: exercise\nBefore we fit a logistic regression model, we are going to explore these data. Let' start with exploring the outcome variable of interest, cholesterol (`income`). For this exercise, we are going to investigate the relationship between `income` and `age`.\n\nLet's calculate the mean and sd of `age` for each level of `income`. What does this tell us? When fitting a logistic regression model, would we expect the probability of making more than \\$50,000 to increase or decrease as you get older?\n\n\n::: {.cell}\n```{webr}\n\n```\n:::\n\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nincome |>\n  group_by(income) |>\n  summarize(\n    mean_age = mean(age),\n    sd_age = sd(age)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  income mean_age sd_age\n  <fct>     <dbl>  <dbl>\n1 <=50K      36.8   14.0\n2 >50K       44.2   10.5\n```\n\n\n:::\n:::\n\n\nThe mean age for those making less than \\$50,000 is roughly 7.4 years younger than the mean age of those making more than \\$50,000. The spread (standard deviation) is also higher for those making less than \\$50,000 in comparison to those making more.\n\nBased on this information, we would expect the probability of making more than \\$50,000 to increase as age increases.\n:::\n\n# Modeling\n\nThe variable `income` in our data set is stored as a `fct`, with the first level being `<=50K`, and second level being `>50K`. Because of this structure, we are going to be modeling the log-odds/probability of `>50K`\n\n::: exercise\nFit a logistic regression model below with income as the outcome and age as the predictor. Compare your output model defined below. Is the outcome the _log-odds_ of making more than \\$50,000 or the _probability_ of making more that \\$50,000?\n:::\n\n\n::: {.cell}\n```{webr}\n\n```\n:::\n\n\n$$\n\\log \\left( \\frac{p}{1-p} \\right) = -2.74 + 0.0395(\\text{age})\n$$\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nincome_model <- logistic_reg() |>\n  fit(income ~ age, data = income, family = binomial)\n\ntidy(income_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic p.value\n  <chr>          <dbl>     <dbl>     <dbl>   <dbl>\n1 (Intercept)  -2.74    0.0427       -64.2       0\n2 age           0.0395  0.000967      40.9       0\n```\n\n\n:::\n:::\n\n\nThe logistic regression model we fit models the log-odds: $$\\log \\left( \\frac{p}{1-p} \\right)$$, where `p` represents the probability of of making more than \\$50,000.\n:::\n\n## Probabilities\n\nTo model the probability of making more than \\$50,000, we need to expoentiate both sides of the eqaution. See below:\n\n$$\np = \\frac{e^{-2.74 + 0.0395(\\text{age})}}{1 + e^{-2.74 + 0.0395(\\text{age})}}\n$$\n\n::: exercise\nUsing your model, what's the probability of making more than \\$50,000 if you are 60 years old in 1994?\n\n\n::: {.cell}\n```{webr}\n\n```\n:::\n\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n$$\np = \\frac{e^{-2.74 + 0.0395(\\text{60})}}{1 + e^{-2.74 + 0.0395(\\text{60})}} = 0.408\n$$\n\nWe can also find this in R!\n\n\n::: {.cell}\n```{webr}\nage_predict <- tibble(age = 61)\n\npredict(income_model$fit, age_predict, type = \"response\") \n```\n:::\n\n\n:::\n\nBased on your concoulsion from your exploratory analysis, does the probabilty of making over \\$50,000 increase or decrease as you age? How can you tell from your model?\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\nThe coefficient assocciated with age is positive, meaning that the estimated probability of making more than \\$50,000 increases as age increases.\n:::\n\nWe can further show your intuition is correct by calculating the probability at the `age` of 61, and see if the difference between the probability at the age of 60 is positive or negative.\n\n$p = \\frac{e^{-2.74 + 0.0395(\\text{61})}}{1 + e^{-2.74 + 0.0395(\\text{61})}} = 0.418$\n\n0.418 - 0.408 = 0.01\n\nThe estimated probability of making more than \\$50,000 increases by roughly 1 percent as you go from age 60 to 61.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](income_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n# Summary \n\n- We can use a logistic regression model to estimate the log-odds/probability of success of the outcome variable.\n\n- The outcome variable must be binary and encoded as a factor.\n\n- We start the model fit with `logistic_reg()` instead of `linear_reg()`.\n\n# Your turn: Challenge\n\nThere are many other variables that could explain the probability of making more than \\$50,000 than just age in 1994. Now, we challenge you to fit a more complicated model to help better understand our variable of interest, `income`.\n\n\n::: {.cell}\n```{webr}\n\n```\n:::\n\n",
    "supporting": [
      "income_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}